name: Update File List

on:
  push:
    branches:
      - main

jobs:
  update-file-list:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Run Script
        run: |
          npm install axios
          node generate-file-list.js

      - name: Commit Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update file list"
          git push https://github.com/${{ github.repository }}.git HEAD:main
        env:
          GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
