name: Update File List

on:
  push:
    branches:
      - main

jobs:
  update-file-list:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Pull the latest changes from the remote repository
      - name: Pull Latest Changes
        run: git pull origin main

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      - name: Run Script to Generate fileList.json
        run: |
          npm install axios
          node generate-file-list.js
        env:
          GITHUB_SHA: ${{ github.sha }}

      # List files in the current directory for debugging
      - name: List Files in Current Directory
        run: ls -al

      # Add fileList.json to the Git staging area
      - name: Add File List to Git
        run: |
          git add fileList.json || echo "No fileList.json found"
          git status
        working-directory: ${{ github.workspace }}

      # Commit and push changes
      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Update fileList.json" || echo "Nothing to commit"
          git push https://github.com/${{ github.repository }}.git HEAD:main
        env:
          GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
